pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Terraform Init') {
            steps {
                dir('terraform/proxmox') {
                    echo 'Initializing Terraform...'
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('terraform/proxmox') {
                    withCredentials([
                        file(credentialsId: 'tfvars', variable: 'TFVARS_FILE'),
                        file(credentialsId: 'ssh_private_key', variable: 'SSH_PRIVATE_KEY')
                    ]) {
                        echo "Setting private key permissions"
                        sh "chmod 600 ${SSH_PRIVATE_KEY}"
                        
                        echo "Copying private key to workspace"
                        sh "cp ${SSH_PRIVATE_KEY} ./id_rsa"
                        
                        echo 'Running Terraform plan...'
                        sh "terraform plan -var-file=${TFVARS_FILE} -var 'SSH_PRIVATE_KEY=./id_rsa' -out=tfplan"
                    }
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('terraform/proxmox') {
                    echo 'Applying Terraform changes...'
                    sh 'terraform apply tfplan'
                }
            }
        }
    }
}